title:               Minjae Kwen
url:                 https://minjaekwen.github.io/
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Minjae Kwen
  url:               minjaekwen.github.io
  email:             kmjaday0082@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist

# ----------------------------------------------------------------------------------------
# 3rd Party Integrations
# ----------------------------------------------------------------------------------------

google_analytics:      G-ZS3DLDQ5JT
